"""create tables

Revision ID: 1dfad11fbee7
Revises: 
Create Date: 2025-04-03 08:24:13.946192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dfad11fbee7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.String(length=10), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('delivery_price', sa.Float(), nullable=True),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    type_table = sa.table('type',
                          sa.Column('id', sa.Integer),
                          sa.Column('name', sa.String)
                          )

    op.bulk_insert(
        type_table,
        [
            {'name': 'одежда'},
            {'name': 'электроника'},
            {'name': 'разное'}
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('package')
    op.drop_table('type')
    # ### end Alembic commands ###
